title: Clément Amiri
show_download: True
theme: jekyll-theme-minimal

# Data Analyst

## Formation
MINES ParisTech PSL Executive Education Datascientest 
Master Psychologie, Université de Lille.
Psychologie des processus neuro cognitifs et sciences affectives

## Research 

Daily Hassles, Coping and Well-Being The Moderating Role of Hemispheric Lateralization
https://lilloa.univ-lille.fr/handle/20.500.12210/102370

Effects of vagal tone modulation via heart rate variability biofeedback on frontal asymmetry score, stress and mood A pilot study.

## Data Project
Modélisation des temps d'intervention des pompiers de Londres
Analyse géographique des votes législatives de la 5ème république 
Test statistique de calibration d'analyseur sanguin pour un laboratoire
Classification de maladie chronique par rapport à des biologiques
Analyse et Visualisations des financements du Centre National Cinématographique
Annotations
